export const setTitle = (payload) => ({ type: 'SET_TITLE', payload });
export const setChartType = (payload) => ({ type: 'SET_CHART_TYPE', payload });
export const setData = (payload) => ({ type: 'SET_DATA', payload });
export const resetState = (payload) => ({ type: 'RESET_STATE', payload });
export const setShowAnnotations = (value) => ({type: 'SET_SHOW_ANNOTATIONS', payload: value,});
export const setVisualizationModelId = (value) => ({type: 'SET_VISUALIZATION_MODEL_ID', payload: value,});
export const setIsAnnotationCustom = (value) => ({type: 'SET_IS_ANNOTATION_CUSTOM', payload: value,});
export const setCustomAnnotation = (value) => ({type: 'SET_CUSTOM_ANNOTATION', payload: value,});
export const setIsFooter = (value) => ({type: 'SET_IS_FOOTER', payload: value,});
export const setFooterText = (value) => ({type: 'SET_FOOTER_TEXT', payload: value,});
export const setAreLabelsVisible = (value) => ({type: 'SET_ARE_LABELS_VISIBLE', payload: value,});
export const setShowGrids = (value) => ({type: 'SET_SHOW_GRIDS', payload: value,});
export const setXAxisLabel = (value) => ({type: 'SET_X_AXIS_LABEL', payload: value,});
export const setYAxisLabel = (value) => ({type: 'SET_Y_AXIS_LABEL', payload: value,});
export const setBackgroundColor = (value) => ({type: 'SET_BACKGROUND_COLOR', payload: value,});
export const setBarColor = (value) => ({type: 'SET_BAR_COLOR', payload: value,});
export const setCustomColors = (value) => ({type: 'SET_CUSOTM_BAR_COLORS', payload: value,});
export const setOpacity = (value) => ({type: 'SET_OPACITY', payload: value,});
export const setBarSpacing = (value) => ({type: 'SET_BAR_SPACING', payload: value,});
export const setFont = (value) => ({type: 'SET_FONT', payload: value,});
export const setTitleSize = (value) => ({type: 'SET_TITLE_SIZE', payload: value,});
export const setArticleSize = (value) => ({type: 'SET_ARTICLE_SIZE', payload: value,});
export const setArticle = (value) => ({type: 'SET_ARTICLE', payload: value,});
export const setTextColor = (value) => ({type: 'SET_TEXT_COLOR', payload: value,});
export const initializeVisualization = (payload) => ({type: "INITIALIZE_VISUALIZATION", payload,});
export const setVisualizationType = (payload) => ({type: "SET_VIZ_TYPE", payload,});
export const setColorPalette = (payload) => ({type: "SET_COLOR_PALETTE", payload,});
export const setShowLegend = (payload) => ({type: "SET_SHOW_LEGEND", payload,});
export const setShowPercentages = (payload) => ({type: "SET_SHOW_PERCENTAGES", payload,});
export const setTransitionTime = (payload) => ({type: "SET_TRANSITION_TIME", payload,});