const initialState = {
  title: '',
  vizType: '',
  colorPalette: 'vibrant',
  xAxisLabel: '',
  yAxisLabel: '',
  showLegend: false,
  showPercentages: false,
  showAnnotations: false,
  data: [[], [], []], 
  filters: [],
  visualizationModelId: null,
  isAnnotationCustom: false,
  customAnnotation: '',
  isFooter: false,
  footerText: 'Source: ',
  areLabelsVisible: true,
  showGrids: false,
  backgroundColor: "#ffffff",
  barColor: "#000000",
  customColors: "",
  opacity: 100,
  barSpacing: 25,
  font: "Arial",
  titleSize: 40,
  articleSize: 16,
  article: "",
  textColor: "#000000",
  transitionTime: 750,
};

export default initialState;