const initialState = {
  title: '',
  chartType: 'bar',
  colorScheme: 'default',
  xAxisLabel: '',
  yAxisLabel: '',
  showLegend: false,
  showAnnotations: false,
  data: [[], [], []], 
  filters: [],
  visualizationModelId: null,
  isAnnotationCustom: false,
  customAnnotation: '',
  isFooter: false,
  footerText: '',
  areLabelsVisible: true,
  showGrids: false,
  backgroundColor: "#ffffff",
  barColor: "#000000",
  customBarColors: "",
  opacity: 100,
  barSpacing: 25,
  font: "Arial",
  titleSize: 40,
  articleSize: 16,
  article: "",
  textColor: "#000000",
};

export default initialState;